# Generated by Django 5.0.1 on 2025-06-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriksPerbandinganKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('kriteria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria1', to='dashboard.kriteria')),
                ('kriteria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria2', to='dashboard.kriteria')),
            ],
        ),
    ]
